services:
  - name: backend-service
    type: web
    env: node
    plan: free
    buildCommand: |
      cd backend-service
      npm install
      cd ../frontend-service
      npm install
      npm run build
      cd ..
    startCommand: |
      cd backend-service
      npm start
    envVars:
      - key: PORT
        value: 3000
    healthCheckPath: /health
